In [1]:
import pandas as pd
import numpy as np
import re
from collections import defaultdict
import datetime
from tqdm import tqdm
import spacy
from multiprocessing import Pool
import pickle
import string

data_path = '../Data/'

In [2]:
nlp = spacy.load('en')

### Importing data

In [29]:
data_1 = pd.read_csv(data_path + 'all-the-news/articles1.csv', encoding = 'utf8')

In [30]:
data_1 = data_1.drop(['Unnamed: 0'], axis = 1)

In [31]:
data_1.head()

,id,title,publication,author,date,year,month,url,content
0,17283,House Republicans Fret About Winning Their Hea...,New York Times,Carl Hulse,2016-12-31,2016.0,12.0,NaN,WASHINGTON — Congressional Republicans have...
1,17284,Rift Between Officers and Residents as Killing...,New York Times,Benjamin Mueller and Al Baker,2017-06-19,2017.0,6.0,NaN,"After the bullet shells get counted, the blood..."
2,17285,"Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...",New York Times,Margalit Fox,2017-01-06,2017.0,1.0,NaN,"When Walt Disney’s “Bambi” opened in 1942, cri..."
3,17286,"Among Deaths in 2016, a Heavy Toll in Pop Musi...",New York Times,William McDonald,2017-04-10,2017.0,4.0,NaN,"Death may be the great equalizer, but it isn’t..."
4,17287,Kim Jong-un Says North Korea Is Preparing to T...,New York Times,Choe Sang-Hun,2017-01-02,2017.0,1.0,NaN,"SEOUL, South Korea — North Korea’s leader, ..."

### Data preprocessing and repartition

- remove punctuations
- lower case everything
- reduce consecutive white spaces
- tokenisation



we repartition the data into intervals of 7 days with a padding period of 23 days:

- this means that for one period, we have 30 days of articles
- the padding is there to ensure the smooth transition between periods
- as well as to ensure we have just slightly more volume, since it is recommended to apply W2V on sufficiently large datasets

In [4]:
data_1.date = [datetime.datetime.strptime(day, '%Y-%m-%d') for day in data_1.date]

We filter the data to only focus on data from 2016

In [26]:
data_1 = data_1[[str(day).split('-')[0] == '2016' for day in data_1.date]].reset_index(drop = True)

remove all non alpha numeric characters

In [27]:
p = Pool(8, maxtasksperchild=1)
tks_1 = p.map(nlp.tokenizer, tqdm(data_1.content))
p.close()

100%|██████████| 28451/28451 [02:13<00:00, 213.81it/s]

data_1.content = [re.sub('[\W_]+', ' ', text).lower().strip() for text in tqdm(data_1.content)]

Tokenisation

We repartition the data

In [54]:
min_date = min(data_1.date)
max_date = max(data_1.date)

In [55]:
min_date, max_date

(Timestamp('2016-01-01 00:00:00'), Timestamp('2016-12-31 00:00:00'))

In [56]:
# we could parallelise/multithread this process if the datasets are much bigger
begin_date = min_date
repartitioned_articles = []
for i in tqdm(range(int((int((max_date - min_date).days) - 30) / 7))):
    articles = data_1[[begin_date <= day < begin_date + datetime.timedelta(days = 30) for day in data_1.date]].content
    #with open(data_path+'all-the-news/articles_1_preprocessed.txt', 'w') as f:
    #    for article in articles:
    #       f.write(' '.join(article) + ' \n')
    begin_date += datetime.timedelta(days = 7)
    repartitioned_articles.append(articles)

  0%|          | 0/47 [00:00<?, ?it/s]
  2%|▏         | 1/47 [00:00<00:09,  4.77it/s]
  4%|▍         | 2/47 [00:00<00:20,  2.20it/s]
  6%|▋         | 3/47 [00:01<00:16,  2.70it/s]
  9%|▊         | 4/47 [00:01<00:14,  3.06it/s]
 11%|█         | 5/47 [00:01<00:12,  3.38it/s]
 13%|█▎        | 6/47 [00:02<00:15,  2.56it/s]
 15%|█▍        | 7/47 [00:02<00:14,  2.75it/s]
 17%|█▋        | 8/47 [00:02<00:13,  2.95it/s]
 19%|█▉        | 9/47 [00:02<00:12,  3.12it/s]
 21%|██▏       | 10/47 [00:03<00:13,  2.74it/s]
 23%|██▎       | 11/47 [00:03<00:12,  2.89it/s]
 26%|██▌       | 12/47 [00:03<00:11,  3.02it/s]
 28%|██▊       | 13/47 [00:04<00:12,  2.72it/s]
 30%|██▉       | 14/47 [00:04<00:11,  2.84it/s]
 32%|███▏      | 15/47 [00:05<00:10,  2.95it/s]
 34%|███▍      | 16/47 [00:05<00:10,  3.03it/s]
 36%|███▌      | 17/47 [00:06<00:10,  2.78it/s]
 38%|███▊      | 18/47 [00:06<00:10,  2.87it/s]
 40%|████      | 19/47 [00:06<00:09,  2.96it/s]
 43%|████▎     | 20/47 [00:06<00:08,  3.04it/s]
 45%|████▍     | 21/47 [00:07<00:09,  2.84it/s]
 47%|████▋     | 22/47 [00:07<00:08,  2.91it/s]
 49%|████▉     | 23/47 [00:07<00:08,  2.98it/s]
 51%|█████     | 24/47 [00:07<00:07,  3.05it/s]
 53%|█████▎    | 25/47 [00:08<00:07,  2.89it/s]
 55%|█████▌    | 26/47 [00:08<00:07,  2.96it/s]
 57%|█████▋    | 27/47 [00:08<00:06,  3.02it/s]
 60%|█████▉    | 28/47 [00:09<00:06,  3.09it/s]
 62%|██████▏   | 29/47 [00:09<00:06,  2.96it/s]
 64%|██████▍   | 30/47 [00:09<00:05,  3.02it/s]
 66%|██████▌   | 31/47 [00:10<00:05,  3.08it/s]
 68%|██████▊   | 32/47 [00:10<00:04,  3.13it/s]
 70%|███████   | 33/47 [00:11<00:04,  3.00it/s]
 72%|███████▏  | 34/47 [00:11<00:04,  3.04it/s]
 74%|███████▍  | 35/47 [00:11<00:03,  3.09it/s]
 77%|███████▋  | 36/47 [00:11<00:03,  3.13it/s]
 79%|███████▊  | 37/47 [00:12<00:03,  3.01it/s]
 81%|████████  | 38/47 [00:12<00:02,  3.05it/s]
 83%|████████▎ | 39/47 [00:12<00:02,  3.10it/s]
 85%|████████▌ | 40/47 [00:13<00:02,  3.00it/s]
 87%|████████▋ | 41/47 [00:13<00:01,  3.05it/s]
 89%|████████▉ | 42/47 [00:13<00:01,  3.10it/s]
 91%|█████████▏| 43/47 [00:13<00:01,  3.15it/s]
 94%|█████████▎| 44/47 [00:14<00:00,  3.05it/s]
 96%|█████████▌| 45/47 [00:14<00:00,  3.10it/s]
 98%|█████████▊| 46/47 [00:14<00:00,  3.14it/s]
100%|██████████| 47/47 [00:14<00:00,  3.19it/s]

We pickle the above file for later use

In [57]:
with open(data_path+'all-the-news/articles_1_preprocessed.pickle', 'wb') as handle:
    pickle.dump(repartitioned_articles, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [24]:
with open(data_path+'all-the-news/articles_1_preprocessed.pickle', 'rb') as handle:
    df = pickle.load(handle)

## Testing out the class

In [1]:
from preprocessing import news_preprocess

In [2]:
prepro = news_preprocess(cores = 8)

In [3]:
data_dir = '../Data/all-the-news/articles1.csv'
prepro.pre_process(data_dir, 'content', 'date', begin = 20170101, end = 20171231)

100%|██████████| 17908/17908 [01:46<00:00, 167.64it/s]
100%|██████████| 17908/17908 [01:00<00:00, 298.30it/s]

training for and detecting bigrams

100%|██████████| 17908/17908 [00:33<00:00, 542.28it/s]

the dataframe is preprocessed successfully

In [4]:
prepro.cut_and_slide(30,7)

100%|██████████| 20/20 [00:02<00:00,  8.53it/s]

articles repartitioned, they can be accessed at self.reparitioned_articles

In [7]:
prepro.save_to_pickle(data_path+'all-the-news/articles_1_')

In [8]:
with open(data_path + '/all-the-news/articles_1_preprocessed.pickle', 'rb') as handle:
    article_lst = pickle.load(handle)

success

In [12]:
len(article_lst)

20

In [13]:
[len(per) for per in article_lst]

[3525,
 3605,
 3548,
 3455,
 3446,
 3364,
 3360,
 3323,
 3207,
 3243,
 3404,
 3589,
 3556,
 3392,
 3037,
 2602,
 2500,
 2410,
 2435,
 2454]

In [15]:
with open(data_path + 'all-the-news/articles_1_1_preprocessed.pickle', 'wb') as handle:
    pickle.dump(article_lst[1],handle)

## testing bigram

In [6]:
from gensim.test.utils import datapath
from gensim.models.word2vec import Text8Corpus
from gensim.models.phrases import Phrases, Phraser

In [7]:
with open(data_path + 'all-the-news/articles_1_0_preprocessed.pickle', 'rb') as handle:
    articles = pickle.load(handle)

In [19]:
phrases = Phrases(articles[:10], min_count=10, threshold=50)

In [20]:
bigram = Phraser(phrases)

In [21]:
print(bigram[articles[1]])

['seoul', 'south_korea', 'north_korea', '’s', 'leader', 'kim', 'said', 'on_sunday', 'that', 'his', 'country', 'was', 'making', 'final', 'preparations', 'to', 'conduct', 'its', 'first', 'test', 'of', 'an_intercontinental', 'ballistic_missile', 'a', 'bold', 'statement', 'less_than', 'a', 'month', 'before', 'the', 'inauguration', 'of', 'donald_j.', 'trump', 'although', 'north_korea', 'has', 'conducted', 'five', 'nuclear', 'tests', 'in', 'the', 'last_decade', 'and', 'more_than', '20', 'ballistic_missile', 'tests', 'in', '2016', 'alone', 'and', 'although', 'it', 'habitually', 'threatens', 'to', 'attack', 'the', 'united_states', 'with', 'nuclear_weapons', 'the', 'country', 'has', 'never', 'an_intercontinental', 'ballistic_missile', 'or', 'icbm', 'in', 'his', 'annual_new', 'year', '’s', 'day', 'speech', 'which', 'was', 'broadcast', 'on', 'the', 'north', '’s', 'kctv', 'on_sunday', 'mr.', 'kim', 'spoke', 'proudly', 'of', 'the', 'strides', 'he', 'said', 'his', 'country', 'had', 'made', 'in', 'its', 'nuclear_weapons', 'and', 'ballistic_missile', 'programs', 'he', 'said', 'north_korea', 'would', 'continue', 'to', 'bolster', 'its', 'weapons', 'programs', 'as', 'long', 'as', 'the', 'united_states', 'remained', 'hostile', 'and', 'continued', 'its', 'joint', 'military', 'exercises', 'with', 'south_korea', 'we', 'have', 'reached', 'the', 'final', 'stage', 'in', 'preparations', 'to', 'an_intercontinental', 'ballistic', 'rocket', 'he', 'said', 'analysts', 'in', 'the', 'region', 'have', 'said', 'mr.', 'kim', 'might', 'conduct', 'another', 'weapons', 'test', 'in', 'coming_months', 'taking', 'advantage', 'of', 'leadership', 'changes', 'in', 'the', 'united_states', 'and', 'south_korea', 'mr._trump', 'will', 'be', 'sworn', 'in', 'on_jan.', '20', 'in', 'south_korea', 'president', 'park', 'whose', 'powers', 'were', 'suspended', 'in', 'a', 'parliamentary', 'impeachment', 'on_dec.', '9', 'is', 'waiting_for', 'the', 'constitutional', 'court', 'to', 'rule', 'on', 'whether', 'she', 'should', 'be', 'formally', 'removed', 'from', 'office', 'or', 'reinstated', 'if', 'north_korea', 'conducts', 'a', 'test', 'in', 'coming_months', 'it', 'will', 'test', 'mr._trump', '’s', 'new', 'administration', 'despite', 'years', 'of', 'increasingly', 'harsh', 'sanctions', 'north_korea', 'has_been', 'advancing', 'toward', 'mr.', 'kim', '’s', 'professed', 'goal', 'of', 'arming', 'his', 'isolated', 'country', 'with', 'the', 'ability', 'to', 'deliver', 'a', 'nuclear', 'warhead', 'to', 'the', 'united_states', 'mr.', 'kim', '’s', 'speech', 'on_sunday', 'indicated', 'that', 'north_korea', 'may', 'a', 'rocket', 'several', 'times', 'this', 'year', 'to', 'complete', 'its', 'icbm', 'program', 'said', 'cheong', 'a', 'senior', 'research', 'fellow_at', 'the', 'sejong', 'institute', 'in', 'south_korea', 'the', 'first', 'of', 'such', 'tests', 'could', 'come', 'even', 'before', 'mr._trump', '’s', 'inauguration', 'mr.', 'cheong', 'said', 'we', 'need', 'to', 'take', 'note', 'of', 'the', 'fact', 'that', 'this', 'is', 'the', 'first', 'new_year', '’s', 'speech', 'where', 'kim', 'mentioned', 'an_intercontinental', 'ballistic_missile', 'he', 'said', 'in', 'his', 'speech', 'mr.', 'kim', 'did_not', 'comment', 'on', 'mr._trump', '’s', 'election', 'doubt', 'still', 'runs', 'deep', 'that', 'north_korea', 'has', 'mastered', 'all', 'the', 'technology', 'needed', 'to', 'build', 'a', 'reliable', 'icbm', 'but', 'analysts', 'in', 'the', 'region', 'said', 'the', 'north', '’s', 'launchings', 'of', 'rockets', 'to', 'put', 'satellites', 'into', 'orbit', 'in', 'recent_years', 'showed', 'that', 'the', 'country', 'had', 'cleared', 'some', 'key', 'technological', 'hurdles', 'after', 'the', 'north', '’s', 'satellite', 'launch', 'in', 'february', 'south', 'korean', 'defense', 'officials', 'said', 'the', 'unha', 'rocket', 'used', 'in', 'the', 'launch', 'if', 'successfully', 'reconfigured', 'as', 'a', 'missile', 'could', 'fly', 'more_than', '7', '400', 'miles', 'with', 'a', 'warhead', 'of', '1', '100', 'to', '1', '300', 'pounds', 'far', 'enough', 'to', 'reach_most', 'of', 'the', 'united_states', 'north_korea', 'has', 'deployed', 'rodong', 'ballistic', 'missiles', 'that', 'can', 'reach_most', 'of', 'south_korea', 'and', 'japan', 'but', 'it', 'has', 'had', 'a', 'spotty', 'record', 'in', 'the', 'musudan', 'its', 'ballistic_missile', 'with', 'a', 'range', 'long', 'enough', 'to', 'reach', 'american', 'military', 'bases', 'in', 'the', 'pacific', 'including', 'those', 'on', 'guam', 'the', 'north', 'has', 'also_claimed', 'a', 'series', 'of', 'successes', 'in', 'testing', 'various', 'icbm', 'technologies', 'although', 'its', 'claims', 'can', 'not', 'be', 'verified', 'and', 'are', 'often', 'disputed', 'by', 'officials', 'and', 'analysts', 'in', 'the', 'region', 'it', 'has', 'said', 'it', 'could', 'now', 'make', 'nuclear_warheads', 'small', 'enough', 'to', 'fit', 'onto', 'a', 'ballistic_missile', 'it', 'also_claimed', 'success', 'in', 'testing', 'the', 'technology', 'that', 'allows', 'a', 'missile', 'to', 'return', 'to', 'the', 'earth', '’s', 'atmosphere', 'without', 'breaking', 'up', 'in', 'april', 'north_korea', 'reported', 'the', 'successful', 'ground_test', 'of', 'an', 'engine', 'for', 'an_intercontinental', 'ballistic_missile', 'at', 'the', 'time', 'mr.', 'kim', 'said', 'the', 'north', 'can', 'tip', 'intercontinental_ballistic', 'rockets', 'with', 'more', 'powerful_nuclear', 'warheads', 'and', 'keep', 'any', 'cesspool', 'of', 'evils', 'in', 'the', 'earth', 'including', 'the', 'u.', 's.', 'mainland', 'within', 'our', 'striking', 'range', 'on', 'sept.', '9', 'the', 'north', 'conducted', 'its', 'fifth', 'and', 'most_powerful', 'nuclear', 'test', 'mr.', 'kim', 'later', 'attended', 'another', 'ground_test', 'of', 'a', 'new', 'rocket_engine', 'exhorting', 'his', 'government', 'to', 'prepare', 'for', 'another', 'rocket', 'launch', 'as', 'soon', 'as', 'possible', 'in', 'november', 'the', 'united', 'nations', 'security', 'council', 'imposed', 'new', 'sanctions', 'against', 'the', 'north']

## Converting json files to dataframe

In [4]:
import jsonlines
#from pprint import pprint
data = []
with jsonlines.open(data_path + 'signalmedia-1m.jsonl', 'r') as reader:
    for entry in reader:
        data.append(entry)

In [17]:
for k,v in data[0].items():
    print('*****',k,'*****')
    print(v)
    print('------------------------------')

***** id *****
f7ca322d-c3e8-40d2-841f-9d7250ac72ca
------------------------------
***** content *****
VETERANS saluted Worcester's first ever breakfast club for ex-soldiers which won over hearts, minds and bellies.

The Worcester Breakfast Club for HM Forces Veterans met at the Postal Order in Foregate Street at 10am on Saturday.

The club is designed to allow veterans a place to meet, socialise, eat and drink, giving hunger and loneliness their marching orders.

Father-of-two Dave Carney, aged 43, of Merrimans Hill, Worcester, set up the club after being inspired by other similar clubs across the country.

He said: "As you can see from the picture, we had a good response. Five out of the 10 that attended said they saw the article in the newspaper and turned up.

"We even had an old chap travel from Droitwich and he was late on parade by three hours.

"It's generated a lot of interest and I estimate (from other veterans who saw the article) that next month's meeting will attract about 20 people. Onwards and upwards."

He said the management at the pub had been extremely hospitable to them.

Mr Carney said: "They bent over backwards for us. They really looked after us well. That is the best choice of venue I could have made. They even put 'reserved for the armed forces'.
   Promoted stories
The reserve veteran with the Royal Engineers wanted to go to a breakfast club but found the nearest ones were in Bromsgrove and Gloucester so he decided to set up his own, closer to home.

He was influenced by Derek Hardman who set up a breakfast club for veterans in Hull and Andy Wilson who set one up in Newcastle. He said the idea has snowballed and there were now 70 similar clubs across the country and even some in Germany.

Mr Carney said with many Royal British Legion clubs closing he wanted veterans and serving personnel to feel they had somewhere they could go for good grub, beer and banter to recapture the comradery of being in the forces.

The Postal Order was chosen because of its central location and its proximity to the railway station and hotels and reasonably priced food and drink.

The management of the pub have even given the veterans a designated area within the pub.

 Share article

The next meeting is at the Postal Order on Saturday, October 3 at 10am.

The breakfast club meets on the first Saturday of each month for those who want to attend in future.
------------------------------
***** title *****
Worcester breakfast club for veterans gives hunger its marching orders
------------------------------
***** media-type *****
News
------------------------------
***** source *****
Redditch Advertiser
------------------------------
***** published *****
2015-09-07T10:16:14Z
------------------------------

In [5]:
df = pd.DataFrame(data)

In [6]:
df.published = [date[:10] for date in df.published]

In [25]:
df.content = [article.replace('\r', ' ') for article in df.content]
df.content = [article.replace('\t', ' ') for article in df.content]

In [12]:
df.head()

,content,id,media-type,published,source,title
0,VETERANS saluted Worcester's first ever breakf...,f7ca322d-c3e8-40d2-841f-9d7250ac72ca,News,2015-09-07,Redditch Advertiser,Worcester breakfast club for veterans gives hu...
1,New Product Gives Marketers Access to Real Key...,609772bc-0672-4db5-8516-4c025cfd54ca,News,2015-09-17,Virtualization Conference & Expo,Jumpshot Gives Marketers Renewed Visibility In...
2,Home »\rStyle » The Return Of The Nike Air Max...,1aa9d1b0-e6ba-4a48-ad0c-66552d896aac,Blog,2015-09-22,Streets Connect,The Return Of The Nike Air Max Sensation Has 8...
3,NYMag.com Daily Intelligencer Vulture The Cut ...,719699f9-47be-4bc7-969b-b53a881c95ae,Blog,2015-09-16,The Cut,This New Dating App Will Ruin Your Internet Game
4,"KUALA LUMPUR, Sept 15 (MySinchew) -- The Kuala...",a080f99a-07d9-47d1-8244-26a540017b7a,News,2015-09-15,My Sinchew,Pay up or face legal action: DBKL

In [26]:
df.to_csv(data_path + 'signal.csv', sep = ',')

In [27]:
pd.read_csv(data_path + 'signal.csv', sep = ',').head(5)

,Unnamed: 0,content,id,media-type,published,source,title
0,0,VETERANS saluted Worcester's first ever breakf...,f7ca322d-c3e8-40d2-841f-9d7250ac72ca,News,2015-09-07,Redditch Advertiser,Worcester breakfast club for veterans gives hu...
1,1,New Product Gives Marketers Access to Real Key...,609772bc-0672-4db5-8516-4c025cfd54ca,News,2015-09-17,Virtualization Conference & Expo,Jumpshot Gives Marketers Renewed Visibility In...
2,2,Home » Style » The Return Of The Nike Air Max ...,1aa9d1b0-e6ba-4a48-ad0c-66552d896aac,Blog,2015-09-22,Streets Connect,The Return Of The Nike Air Max Sensation Has 8...
3,3,NYMag.com Daily Intelligencer Vulture The Cut ...,719699f9-47be-4bc7-969b-b53a881c95ae,Blog,2015-09-16,The Cut,This New Dating App Will Ruin Your Internet Game
4,4,"KUALA LUMPUR, Sept 15 (MySinchew) -- The Kuala...",a080f99a-07d9-47d1-8244-26a540017b7a,News,2015-09-15,My Sinchew,Pay up or face legal action: DBKL

In [18]:
import csv
with open(r"../Data/signal.csv", 'r') as f:
    reader = csv.reader(f)
    linenumber = 1
    try:
        for row in reader:
            linenumber += 1
    except Exception as e:
        print (("Error line %d: %s %s" % (linenumber, str(type(e)), e.message)))

In [19]:
[i for i, article in enumerate(df.content) if '\r' in article]

[2,
 27,
 29,
 32,
 35,
 44,
 52,
 61,
 75,
 81,
 82,
 87,
 90,
 92,
 93,
 105,
 129,
 133,
 136,
 137,
 138,
 140,
 149,
 184,
 185,
 196,
 211,
 229,
 263,
 280,
 289,
 291,
 297,
 309,
 311,
 312,
 313,
 316,
 319,
 320,
 331,
 343,
 344,
 354,
 362,
 370,
 376,
 386,
 394,
 404,
 405,
 437,
 440,
 443,
 451,
 458,
 459,
 461,
 468,
 485,
 495,
 510,
 512,
 528,
 530,
 538,
 566,
 584,
 589,
 609,
 615,
 617,
 636,
 640,
 653,
 672,
 673,
 690,
 693,
 697,
 728,
 738,
 743,
 762,
 764,
 768,
 781,
 785,
 798,
 801,
 813,
 815,
 818,
 819,
 822,
 829,
 835,
 853,
 855,
 856,
 860,
 870,
 872,
 893,
 895,
 901,
 907,
 928,
 944,
 959,
 961,
 982,
 1004,
 1020,
 1053,
 1055,
 1069,
 1084,
 1115,
 1118,
 1125,
 1136,
 1139,
 1143,
 1151,
 1178,
 1181,
 1186,
 1198,
 1207,
 1211,
 1225,
 1233,
 1235,
 1245,
 1249,
 1255,
 1261,
 1263,
 1292,
 1302,
 1303,
 1304,
 1305,
 1319,
 1333,
 1336,
 1351,
 1358,
 1359,
 1366,
 1369,
 1375,
 1377,
 1394,
 1416,
 1430,
 1448,
 1473,
 1488,
 1494,
 1497,
 1498,
 1503,
 1504,
 1507,
 1509,
 1516,
 1520,
 1523,
 1526,
 1546,
 1558,
 1569,
 1580,
 1582,
 1586,
 1593,
 1594,
 1597,
 1598,
 1606,
 1609,
 1618,
 1624,
 1625,
 1628,
 1663,
 1682,
 1685,
 1690,
 1717,
 1720,
 1749,
 1750,
 1764,
 1766,
 1769,
 1773,
 1777,
 1780,
 1782,
 1815,
 1816,
 1824,
 1842,
 1848,
 1859,
 1862,
 1863,
 1867,
 1868,
 1875,
 1877,
 1908,
 1918,
 1920,
 1939,
 1941,
 1959,
 1965,
 1969,
 1977,
 1988,
 1990,
 1991,
 2006,
 2007,
 2017,
 2021,
 2034,
 2054,
 2057,
 2087,
 2097,
 2098,
 2099,
 2126,
 2133,
 2143,
 2156,
 2165,
 2170,
 2178,
 2189,
 2206,
 2211,
 2221,
 2227,
 2247,
 2249,
 2250,
 2260,
 2262,
 2268,
 2271,
 2276,
 2288,
 2300,
 2303,
 2312,
 2335,
 2341,
 2345,
 2353,
 2355,
 2360,
 2376,
 2382,
 2394,
 2404,
 2412,
 2414,
 2418,
 2430,
 2446,
 2459,
 2480,
 2485,
 2494,
 2514,
 2518,
 2536,
 2566,
 2568,
 2576,
 2577,
 2583,
 2594,
 2598,
 2606,
 2612,
 2622,
 2630,
 2642,
 2648,
 2655,
 2671,
 2673,
 2679,
 2680,
 2681,
 2682,
 2683,
 2696,
 2702,
 2706,
 2713,
 2720,
 2743,
 2747,
 2753,
 2757,
 2759,
 2761,
 2767,
 2783,
 2789,
 2794,
 2795,
 2812,
 2814,
 2818,
 2823,
 2828,
 2843,
 2845,
 2854,
 2871,
 2874,
 2878,
 2879,
 2888,
 2903,
 2912,
 2919,
 2938,
 2952,
 2958,
 2963,
 2965,
 2966,
 2987,
 2989,
 2996,
 2998,
 3026,
 3028,
 3029,
 3039,
 3063,
 3073,
 3104,
 3123,
 3126,
 3132,
 3138,
 3140,
 3142,
 3145,
 3150,
 3153,
 3173,
 3175,
 3178,
 3179,
 3191,
 3211,
 3219,
 3225,
 3240,
 3265,
 3266,
 3284,
 3291,
 3299,
 3302,
 3309,
 3313,
 3320,
 3329,
 3343,
 3346,
 3347,
 3353,
 3363,
 3364,
 3365,
 3380,
 3398,
 3399,
 3400,
 3401,
 3402,
 3404,
 3418,
 3452,
 3453,
 3457,
 3459,
 3472,
 3487,
 3498,
 3516,
 3520,
 3544,
 3555,
 3556,
 3570,
 3577,
 3584,
 3586,
 3590,
 3595,
 3596,
 3597,
 3617,
 3627,
 3641,
 3643,
 3668,
 3705,
 3713,
 3718,
 3721,
 3723,
 3734,
 3736,
 3754,
 3784,
 3787,
 3792,
 3812,
 3826,
 3834,
 3842,
 3881,
 3884,
 3895,
 3908,
 3909,
 3919,
 3959,
 3969,
 3977,
 4006,
 4007,
 4010,
 4019,
 4033,
 4038,
 4059,
 4060,
 4070,
 4073,
 4075,
 4078,
 4090,
 4092,
 4093,
 4102,
 4115,
 4125,
 4128,
 4134,
 4148,
 4151,
 4169,
 4170,
 4178,
 4181,
 4189,
 4214,
 4222,
 4229,
 4230,
 4237,
 4248,
 4263,
 4265,
 4274,
 4277,
 4278,
 4279,
 4297,
 4311,
 4314,
 4325,
 4339,
 4362,
 4370,
 4376,
 4387,
 4408,
 4418,
 4421,
 4427,
 4462,
 4465,
 4469,
 4473,
 4487,
 4491,
 4505,
 4531,
 4533,
 4555,
 4581,
 4583,
 4596,
 4613,
 4617,
 4618,
 4631,
 4650,
 4664,
 4694,
 4701,
 4719,
 4721,
 4722,
 4724,
 4736,
 4740,
 4764,
 4776,
 4784,
 4800,
 4804,
 4809,
 4831,
 4837,
 4857,
 4874,
 4889,
 4903,
 4905,
 4930,
 4935,
 4941,
 4944,
 4951,
 4959,
 4965,
 4985,
 4998,
 5010,
 5014,
 5020,
 5027,
 5045,
 5046,
 5050,
 5056,
 5060,
 5066,
 5076,
 5087,
 5088,
 5089,
 5105,
 5124,
 5136,
 5146,
 5188,
 5197,
 5237,
 5249,
 5252,
 5278,
 5289,
 5302,
 5306,
 5316,
 5326,
 5330,
 5332,
 5342,
 5352,
 5371,
 5374,
 5379,
 5385,
 5392,
 5414,
 5416,
 5421,
 5429,
 5430,
 5431,
 5441,
 5446,
 5463,
 5480,
 5489,
 5494,
 5495,
 5513,
 5516,
 5527,
 5533,
 5542,
 5554,
 5572,
 5577,
 5582,
 5587,
 5592,
 5593,
 5603,
 5618,
 5620,
 5622,
 5625,
 5630,
 5631,
 5655,
 5669,
 5706,
 5707,
 5730,
 5732,
 5734,
 5736,
 5746,
 5754,
 5769,
 5770,
 5779,
 5781,
 5785,
 5787,
 5790,
 5794,
 5797,
 5819,
 5825,
 5834,
 5850,
 5857,
 5868,
 5884,
 5889,
 5895,
 5900,
 5902,
 5903,
 5910,
 5945,
 5948,
 5953,
 5954,
 5988,
 5992,
 5994,
 5995,
 6002,
 6005,
 6009,
 6020,
 6031,
 6035,
 6036,
 6042,
 6053,
 6074,
 6076,
 6081,
 6110,
 6114,
 6129,
 6131,
 6144,
 6160,
 6161,
 6166,
 6175,
 6178,
 6184,
 6186,
 6194,
 6198,
 6201,
 6229,
 6231,
 6243,
 6245,
 6258,
 6260,
 6265,
 6281,
 6292,
 6297,
 6307,
 6315,
 6332,
 6334,
 6336,
 6339,
 6350,
 6355,
 6356,
 6363,
 6385,
 6401,
 6414,
 6416,
 6425,
 6456,
 6460,
 6471,
 6473,
 6474,
 6483,
 6493,
 6497,
 6501,
 6514,
 6520,
 6523,
 6527,
 6548,
 6578,
 6597,
 6600,
 6602,
 6606,
 6609,
 6610,
 6616,
 6617,
 6619,
 6620,
 6621,
 6625,
 6626,
 6629,
 6630,
 6632,
 6639,
 6666,
 6675,
 6680,
 6685,
 6687,
 6692,
 6693,
 6696,
 6699,
 6730,
 6736,
 6747,
 6751,
 6752,
 6753,
 6760,
 6762,
 6774,
 6776,
 6787,
 6802,
 6809,
 6810,
 6812,
 6813,
 6819,
 6823,
 6851,
 6871,
 6894,
 6897,
 6907,
 6908,
 6918,
 6922,
 6937,
 6940,
 6949,
 6969,
 6982,
 6984,
 6994,
 7011,
 7074,
 7077,
 7084,
 7089,
 7109,
 7111,
 7120,
 7123,
 7124,
 7139,
 7142,
 7145,
 7160,
 7164,
 7171,
 7183,
 7217,
 7232,
 7234,
 7251,
 7258,
 7259,
 7302,
 7333,
 7334,
 7335,
 7358,
 7361,
 7367,
 7368,
 7370,
 7385,
 7390,
 7400,
 7403,
 7411,
 7413,
 7431,
 7439,
 7449,
 7450,
 7464,
 7466,
 7470,
 7472,
 7493,
 7503,
 7504,
 7514,
 7528,
 7530,
 7545,
 7550,
 7554,
 7555,
 7559,
 7564,
 7571,
 7576,
 7592,
 7598,
 7606,
 7627,
 7632,
 7656,
 7659,
 7671,
 7685,
 7691,
 7697,
 7700,
 7702,
 7728,
 7748,
 7753,
 7755,
 7756,
 7764,
 7767,
 7773,
 7775,
 7794,
 7798,
 7803,
 7813,
 7837,
 7842,
 7844,
 7853,
 7905,
 7915,
 7927,
 7945,
 7957,
 7959,
 7963,
 7967,
 7971,
 7975,
 7977,
 7993,
 8009,
 8020,
 8038,
 8040,
 8051,
 8053,
 8056,
 8066,
 8098,
 8107,
 8112,
 8129,
 8162,
 8170,
 8171,
 8177,
 8192,
 8202,
 8210,
 8213,
 8226,
 8238,
 8252,
 8263,
 8269,
 8289,
 8292,
 8311,
 8319,
 8336,
 8354,
 8355,
 8358,
 8376,
 8380,
 8382,
 8391,
 8401,
 8409,
 8411,
 8412,
 8420,
 8424,
 8448,
 8463,
 8473,
 8478,
 8482,
 8491,
 8517,
 8521,
 8534,
 8551,
 8565,
 8578,
 8589,
 8610,
 8620,
 8623,
 8633,
 8639,
 8644,
 8664,
 8672,
 8683,
 8702,
 8707,
 8708,
 8716,
 8723,
 8730,
 8737,
 8741,
 8744,
 8754,
 8758,
 8796,
 8799,
 8803,
 8807,
 8809,
 8811,
 8819,
 8827,
 8846,
 8862,
 8884,
 8885,
 8889,
 8916,
 8918,
 8926,
 8929,
 8933,
 8942,
 8946,
 8954,
 8977,
 8988,
 8996,
 8998,
 8999,
 9009,
 9011,
 9026,
 9032,
 9053,
 9065,
 9068,
 9077,
 9082,
 9099,
 9105,
 9123,
 9129,
 9132,
 ...]

In [22]:
df.content[2]

'Home » Style » The Return Of The Nike Air Max Sensation Has 80’s Babies Hyped!\tPosted on Sep 22, 2015 If you were a basketball fan who was born in the 80s, you were lucky enough to witness the beauty that is 90s basketball. It was truly a great time to be basketball fan. If you played close attention to what the players were wearing on their feet you would have also noticed the wide array of footwear these player used to rock. One of those happens to the the Nike Air Max Sensation, which is also set to receive the retro treatment this year! Originally released back in …read more Author: KicksOnFire\tShare This Post On GoogleFacebookTwitter'